---
title: "Q3"
author: "Yuxin Du 1004174350"
date: "04/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(astsa)
temp  =  tempr−mean( tempr )#center  temperature
temp2  =  temp^2
trend =time( cmort ) #time
fit = lm(cmort~trend+temp+temp2+part,na.action=NULL)
summary(fit )

NEW =ts.intersect(cmort,part4=lag(part,-4),trend,temp,temp2,part,dframe=TRUE)

summary(fit_new<-lm(cmort~part4+trend+temp+temp2+part ,data = NEW,na.action=NULL))

pairs(cbind(ts.intersect(cmort,part4=lag(part,-4),trend,temp,temp2,part,dframe=TRUE)))
                
num = length(cmort) # sample size
AIC(fit)/num - log(2*pi) # AIC
BIC(fit)/num - log(2*pi) # BIC

AIC(fit_new)/num - log(2*pi) # AIC
BIC(fit_new)/num - log(2*pi) # BIC
```
sigma square1=6.385
sigma square2=6.287 
Residual sum of square is smaller, which means the model2 fits better.
According to the results, we find that AIC and BIC of the model 2 is smaller than that of model 1, which means mode2 is better than model1
